name: 'Terraform Cloud'

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]
    
jobs:

  Terraform:
    name: 'Terraform Cloud'
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        # terraform_version: 0.13.0
        cli_config_credentials_token: ${{ secrets.TERRAFORM_API_TOKEN }}
      
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      working-directory: './terraform-cloud'

    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: './terraform-cloud'

    - name: Terraform Validate
      id: validate
      run: terraform validate
      working-directory: './terraform-cloud'

    - name: Terraform Plan
      id: plan
      if: github.event_name == 'pull_request'
      run: terraform plan
      continue-on-error: true
      working-directory: './terraform-cloud'

    - name: 'Terraform Apply'
      id: apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -no-color -var=prefix=kdidi${{github.run_number}}
      working-directory: './terraform-cloud'